package br.com.Constantes;

public enum CONSTANTES {

	STATUS_ATIVO, STATUS_INATIVO, FINANCEIRO_A_PAGAR, FINANCEIRO_PAGO, FINANCEIRO_VENCIDO, PETICAO_01, PETICAO_02,
	PETICAO_03, PETICAO_04, PETICAO_05;

}
